#!/usr/bin/env sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

## Open widgets
run_eww() {
      eww open-many \
           home \
           disk \
           downloads \
           pictures \
           documents \
           favourite \
           bgbox
}

close_eww() {
	eww close \
           home \
           disk \
           downloads \
           pictures \
           documents \
           favourite \
           bgbox
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE" &&
	run_eww

else
	close_eww
	rm "$FILE"
fi
