#!/usr/bin/env sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
run_mus() {
    ${EWW} open \
           player
}

close_mus() {
    ${EWW} close \
           player
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_mus
else
    close_mus
    rm "$FILE"
fi
