#!/usr/bin/env sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
run_vol() {
    ${EWW} open \
            volume
    }

close_vol() {
    ${EWW} close \
           volume
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_vol
else
    close_vol
    rm "$FILE"
fi
