#!/usr/bin/env sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
run_app() {
    ${EWW} open-many \
           home \
           disk \
           downloads \
           pictures \
           documents \
           favourite
}

close_app() {
    ${EWW} close \
           home \
           disk \
           downloads \
           pictures \
           documents \
           favourite
}
## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_app
else
    close_app
    rm "$FILE"
fi
